# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('Kanto', 'Kanto'), ('Johto', 'Johto'), ('Hoenn', 'Hoenn'), ('Sinnoh', 'Sinnoh'), ('Unova', 'Unova'), ('Kalos', 'Kalos'), ('Alola', 'Alola')], default='Kanto', max_length=31),
        ),
    ]
