# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20180128_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('symbol', models.CharField(max_length=31)),
            ],
        ),
    ]
