# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-14 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_nature_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.Region')),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type_primary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_primary', to='pokemon.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type_secondary',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_secondary', to='pokemon.Type'),
        ),
    ]
