# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-14 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20171014_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
