# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20171014_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type_secondary',
            field=models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_secondary', to='pokemon.Type'),
        ),
    ]
