# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-15 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20171014_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type_secondary',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_secondary', to='pokemon.Type'),
        ),
    ]
