# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_auto_20171015_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('power_points', models.IntegerField()),
                ('accuracy', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('None', 'None'), ('Normal', 'Normal'), ('Fighting', 'Fighting'), ('Flying', 'Flying'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Rock', 'Rock'), ('Bug', 'Bug'), ('Ghost', 'Ghost'), ('Steel', 'Steel'), ('Fire', 'Fire'), ('Water', 'Water'), ('Grass', 'Grass'), ('Electric', 'Electric'), ('Psychic', 'Psychic'), ('Ice', 'Ice'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Fairy', 'Fairy')], default='Normal', max_length=64),
        ),
        migrations.AddField(
            model_name='moves',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.Type'),
        ),
    ]
