# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_auto_20171015_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('HP', 'HP'), ('Attack', 'Attack'), ('Defense', 'Defense'), ('Special Attack', 'Special Attack'), ('Special Defense', 'Special Defense'), ('Speed', 'Speed')], default='HP', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('-', '-'), ('Normal', 'Normal'), ('Fighting', 'Fighting'), ('Flying', 'Flying'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Rock', 'Rock'), ('Bug', 'Bug'), ('Ghost', 'Ghost'), ('Steel', 'Steel'), ('Fire', 'Fire'), ('Water', 'Water'), ('Grass', 'Grass'), ('Electric', 'Electric'), ('Psychic', 'Psychic'), ('Ice', 'Ice'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Fairy', 'Fairy')], default='Normal', max_length=64),
        ),
    ]
