# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_auto_20171015_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moves',
            new_name='Move',
        ),
    ]
