# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_auto_20171015_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(choices=[('-', '-'), ('HP', 'HP'), ('Attack', 'Attack'), ('Defense', 'Defense'), ('Special Attack', 'Special Attack'), ('Special Defense', 'Special Defense'), ('Speed', 'Speed')], default='HP', max_length=64),
        ),
    ]
