# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_auto_20171015_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='accuracy',
            field=models.CharField(default='100', max_length=50),
        ),
        migrations.AlterField(
            model_name='move',
            name='power',
            field=models.CharField(default='20', max_length=50),
        ),
    ]
