# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_auto_20171015_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='symbol',
            field=models.CharField(default='Circle', max_length=64),
        ),
    ]
