# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_stat_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='fully_evolved',
            field=models.BooleanField(default=False),
        ),
    ]
